---
- name: Install Apache2 
  hosts: S1
  tasks:
    - name: Install Apache2
      become: yes
      apt:
        name: apache2
        state: present
- name: Install Nginx  
  hosts: S2
  tasks:
    - name: Install Nginx
      become: yes
      apt:
        name: nginx
        state: present
